In [1]:
import numpy as np

print(np.__version__)

2.5.1


In [2]:
lista = [1, 2, 3, 4, 5]
type(lista)

list

In [3]:
array = np.array(lista)
type(array)

numpy.ndarray

In [4]:
lista / 2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [5]:
array / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [6]:
lista * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [7]:
array * 2

array([ 2,  4,  6,  8, 10])

In [8]:
# convertir lista a array
lista = [1, 2, 3, 4, 5]
array = np.array(lista)
print(array)
print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
lista_decimales = [1.5, 2.5, 3.5, 4.5, 5.5]
arr_decimales = np.array(lista_decimales)
print(arr_decimales)
print(type(arr_decimales))
print(arr_decimales.dtype)  # tipo de datos del array

[1.5 2.5 3.5 4.5 5.5]
<class 'numpy.ndarray'>
float64


In [11]:
lista_enteros = [1, 2, 3, 4, 5]
arr_enteros = np.array(lista_enteros)
print(arr_enteros)
print(arr_enteros.dtype)  # tipo de datos del array

[1 2 3 4 5]
int64


In [12]:
lista_enteros = [1, 2, 3, 4, 5]
arr_enteros = np.array(lista_enteros, dtype=np.float64)  # especificar tipo de datos
print(arr_enteros)
print(arr_enteros.dtype)  # tipo de datos del array

[1. 2. 3. 4. 5.]
float64


In [13]:
arr_float = arr_enteros.astype(np.float64)  # convertir a float64
print(arr_float)
print(arr_float.dtype)  # tipo de datos del array

[1. 2. 3. 4. 5.]
float64


In [14]:
arr_str = arr_enteros.astype(str)  # convertir a string
print(arr_str)
print(arr_str.dtype)  # tipo de datos del array

['1.0' '2.0' '3.0' '4.0' '5.0']
<U32


### Dimensiones

In [15]:
# ESCALAR
scalar = np.array(50)
print(scalar)
print(type(scalar))
print(scalar.ndim)  # número de dimensiones

50
<class 'numpy.ndarray'>
0


In [16]:
# VECTOR
vector = np.array([1, 2, 3, 4, 5])
print(vector)
print(type(vector))
print(vector.ndim)  # número de dimensiones

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [18]:
# MATRIZ
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)
print(type(matrix))
print(matrix.ndim)  # número de dimensiones

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2


### Generación de números aleatorios

In [19]:
np.arange(0, 20, 2)  # rango de valores con paso de 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
np.zeros(5, dtype="int64")  # array de ceros de tamaño 5 y tipo int64

array([0, 0, 0, 0, 0])

In [21]:
np.zeros((3, 4), dtype="float64")  # array de ceros de tamaño 3x4 y tipo float64

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones(5, dtype="int64")  # array de unos de tamaño 5 y tipo int64

array([1, 1, 1, 1, 1])

In [23]:
np.ones((3, 4), dtype="float64")  # array de unos de tamaño 3x4 y tipo float64

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.ones((3, 10, 2), dtype="float64")  # array de unos de tamaño 3x10x2 y tipo float64

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [25]:
np.eye(3)  # matriz identidad de tamaño 3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])